import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dynamic from 'next/dynamic';
import FooterComponent from "@/components/FooterComponent";
import HeaderComponent from "@/components/HeaderComponent";

// Dynamically import WelcomePopup with SSR disabled to prevent hydration issues
const WelcomePopup = dynamic(() => import('@/components/WelcomePopup'), {
  ssr: false,
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "dpboss24",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
      >
        <SessionProvider>
          <HeaderComponent />
          {children}
          <FooterComponent />
          <WelcomePopup />
        </SessionProvider>
      </body>
    </html>
  );
}
